// Code generated by "stringer -type=CurrencyType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecified-0]
	_ = x[Bitcoin-1]
	_ = x[Ethereum-2]
}

const _CurrencyType_name = "UnspecifiedBitcoinEthereum"

var _CurrencyType_index = [...]uint8{0, 11, 18, 26}

func (i CurrencyType) String() string {
	if i >= CurrencyType(len(_CurrencyType_index)-1) {
		return "CurrencyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CurrencyType_name[_CurrencyType_index[i]:_CurrencyType_index[i+1]]
}
