name: Bug Report
description: Create a report to help us improve Phonon client.
labels: [bug]
body:
  - type: textarea
    id: problem_statement
    attributes:
      label: Problem
      description: A clear and concise description of what the bug is. The more information you provide, the easier it is for us to reproduce the bug.
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
  - type: textarea
    id: reproducible_steps
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: os
    attributes:
      label: OS
      description: What operating system does this bug occur on?
  - type: textarea
    id: browsers
    attributes:
      label: Browsers
      description: The browser(s) that this problem occurs in
      placeholder: |
        Example:
        - Chrome 90.0.4430.212
        - Firefox 88.0.1
  - type: textarea
    id: logs
    attributes:
      label: Log output and Stacktrace
      render: shell
