name: Bug Report
description: Create a report to help us improve Phonon client.
labels: [feature]
body:
  - type: textarea
    id: description
    attributes:
      label: description
      description: A clear and concise description of what feature you wish to have implemented. The more information you provide, the easier it is for us to know what you wish to have implemented.
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
  - type: textarea
    id: rationale
    attributes:
      label: reason you want this implemented
