name: Refactoring Request
description: Suggest a refactor to the phonon-client
labels: [feature]
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: A clear and concise description of the code to be refactored. The more information you provide, the easier it is for us to know what you wish to have chaanged.
  - type: textarea
    id: Rationale
    attributes:
      label: Reason you want this implemented
